version: '3.9'

services:
  businessapp:
    container_name: ds-backend-app
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3030:3030"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    networks:
      - ds-network

  mongo:
    container_name: ds-database-app
    image: mongo:latest
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ds-network

  nginx:
    container_name: ds-nginx-app
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - businessapp
    networks:
      - ds-network

volumes:
  mongo_data: 

networks:
  ds-network:
    driver: bridge